import React from "react";
import { Checklist, DarkCta, Hero, MediaImage, MiniList, SectionTitle, Stat, SubsidyCard } from "../components/ui";
import { productPanelsImage, serviceEngineeringLiaisonImage, serviceSolarInstallImage, serviceHeroImage, solarEngineersInspectionImage } from "../assets";

function ServicesPage({ navigate, setModal }) {
  return (
    <main className="services-page">
      <Hero className="hero-services split-hero" bgImage={serviceHeroImage} eyebrow="End-to-End Excellence" title="Comprehensive Energy Solutions for a Sustainable Future" copy="From residential rooftops to utility-scale open access, we provide end-to-end solar engineering, procurement, and construction services." primary="Contact Our Experts" onPrimary={() => setModal("contact")} sideImage={serviceHeroImage} />
      <section className="split-section align-start"><div className="editorial-copy"><p className="eyebrow blue">Residential Solutions</p><h2>PM Surya Ghar Subsidy Scheme</h2><p>Looking to solarize your home? Iayan Solar helps you take advantage of the PM Surya Ghar Subsidy Scheme with expert guidance and high-quality solar solutions.</p><MiniList items={["Bank Finance: Up to 100% without collateral for amounts up to ₹2,00,000 at 7% interest rate", "Affordable EMIs: Pay less than your current electricity bills and enjoy freedom from rising energy costs", "Expert Solutions: Customized home solar solutions with high-quality Balance of System (BOS) components"]} /></div><SubsidyCard onCheck={() => setModal("eligibility")} /></section>
      <section className="split-section section-grey"><div className="media-frame with-percent"><MediaImage src={solarEngineersInspectionImage} type="engineer" /><div className="percent-box"><strong>18% to 40%</strong><span>Return on investment</span></div></div><div className="editorial-copy"><p className="eyebrow muted">Enterprise Grade</p><h2>Rooftop Solar Power Plant:</h2><p>Maximize your unused rooftop space by installing a customized solar power plant.</p><p>We cater to all types of users – residential, commercial, educational institutions, group housing, and industries.</p><p>From consultation to design, engineering, supply, installation, approvals, and full operations & maintenance, we stay with you throughout the entire lifecycle of your solar power plant.</p><p>Experience reliable, highly tested, and top-quality products and services tailored to your needs. We don’t believe in one-size-fits-all solutions; instead, we deliver customized solutions that truly address your energy requirements.</p><p>Enjoy a return on investment of 18% to 40% depending on the project, along with accelerated asset depreciation benefits of 40% to 60%.</p></div></section>
      <section className="dark-section split-section open-access-showcase"><div className="editorial-copy open-access-copy"><p className="eyebrow muted">Utility Scale</p><h2>Open Access Solar Power Plant:</h2><div className="service-story-flow"><p>Generate your own energy and supply it directly to consumers (exclusive for HT consumers) with Life Bess Solar.</p><p>Life Bess  offer high yield and flexibility, allowing you to adjust units across different consumption slots efficiently.</p><p>From consultation to deal With on-site O&M personnel from Life Bess , we ensure continuous monitoring and delivery of uninterrupted, clean energy.sign, engineering, supply, installation, approvals, and full operations & maintenance, we stay with you throughout the entire lifecycle of your solar power plant.</p><p>Scalable from 1 MW to hundreds of MW, Life Bess Associated Solar plants are designed to grow with your energy needs.</p></div><div className="finance-row open-access-stats"><Stat value="16% to 35%" label="Return on Investment" /><Stat value="40% to 60%" label="Accelerated Asset Depreciation" /></div></div><div className="dark-card editorial-copy open-access-finance"><h3>Financial Benefits:</h3><div className="finance-detail-list"><p>Return on Investment: 16% to 35% (case by case)</p><p>Accelerated Asset Depreciation: 40% to 60%</p><p>Types of Power Plants by Iayan Solar: Captive: For self-consumption, Group Captive: For a group of entities with shared self-consumption, Third-Party: Sell energy at competitive rates, lower than TANGEDCO</p><p>Comprehensive Services from Life Bess Solar Include: 1) Site identification and feasibility assessment 2) Liaison with TANGEDCO and necessary approvals 3) Development of power transmission infrastructure 4) Engineering, design, and construction of the solar power plant 5) Operations, maintenance, and energy audits</p></div></div></section>
      <section className="section"><SectionTitle eyebrow="Investment Models" title="Zero Capex Power Purchase" /><div className="three-grid plans"><article className="plan-card"><h3>1. Third Party</h3><p>Attracts Cross Subsidy Surcharge and other Open Access charges,</p><p>Save approximately ₹0.50 to ₹1.4 per unit, depending on the type of connection.</p></article><article className="plan-card featured"><h3>2. Group Captive</h3><p>Attracts only Open Access charges,</p><p>Save approximately ₹1.5 to ₹2 per unit, depending on the type of connection.</p></article><article className="plan-card"><h3>3. Invest Zero</h3><p>No investment required on your part,</p><p>The plant investors will sell power at lower rates,</p><p>Only a bank guarantee (BG) for 3 months of the estimated bill is needed.</p></article></div></section>
      <section className="section section-grey"><p className="eyebrow blue">Service Continuity</p><h2>Operations & Maintenance</h2><div className="two-grid"><MiniList items={["Rooftop Solar Power Plants – Residential, commercial, and institutional setups", "Open Access Solar Power Plants – Captive, Group Captive, and Third-Party models", "Zero Capex Power Purchase Models – Benefit from solar energy without any upfront investment", "Off-Grid & On-Grid Systems, Solar DC Microgrids, Solar Street Lights, and Solar Water Pumping Systems"]} /><div className="editorial-copy"><p>With a focus on sustainability and efficiency, Life Bess Solar employs advanced monitoring and maintenance techniques to maximize energy output, minimize downtime, and ensure your solar systems deliver reliable, uninterrupted clean energy throughout their lifecycle.</p><MediaImage src={serviceSolarInstallImage || productPanelsImage} type="panels" className="short-media" /></div></div></section>
      <section className="split-section"><div className="media-frame"><MediaImage src={serviceEngineeringLiaisonImage} type="building" /></div><div className="editorial-copy"><p className="eyebrow blue">Global Sustainability</p><h2>Carbon Credit</h2><Checklist items={["Certified Process: Follow globally recognized procedures", "Testable & Verifiable: Easily validated by an international audience", "Business Advantage: Enhance global business opportunities by reducing the carbon footprint of your products or services", "Tradable Carbon Credits: Carbon credits can be bought, sold, or traded to maximize benefits"]} /><p>With Life Bess Solar, your business can go green, gain credibility, and unlock global opportunities.</p><button className="button button-dark" onClick={() => navigate("quote")}>Start Your Carbon Audit</button></div></section>
      <section className="section section-grey product-strip-section"><SectionTitle eyebrow="Our Products" title="Our Products:" /><div className="product-name-grid"><span>Solar Panels</span><span>Solar Inverters</span><span>Solar Batteries ( Lithium/Lead Acid Batteries )</span><span>All Solar Accessories</span><span>MMS/Structures</span><span>Solar Street lights</span><span>Solar Water Heaters</span><span>Solar Mini Home Kits etc.</span></div></section>
      <DarkCta image={serviceHeroImage} title="Ready for a transition?" copy="Speak with our energy consultants today for a customized feasibility report and financial projection." button="Request a Quote" onClick={() => navigate("quote")} />
    </main>
  );
}

export { ServicesPage };
